[package]
name = "can_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "can_test"
crate-type = ["cdylib"]

[dependencies]
linuxfb = "0.3.1"
pyo3 = "0.23.1"
